### ISSUE TITLE
准备新增或修改的汉字

### ISSUE THREAD

**Issue by Buernia** [Buernia/Tiejili#1]
修改：
- [x] 延褝

新增：

- [x] 㓥㘵㝹㞎㞗㤭㨃㭴㵲㶉㹴㻋䃟䙆乪佉佢僜冇厔吔呾咁咗哖啲喺嗮嗰嘅嘢嚟囍垝奀屄屌昚昰曱朆氹焿煚熯牠琍甴皝盩睺砯礽祂禟禩肏脷膥舺菈襈覅豗贠跩迌饤饾髈鹓鼟𠊎𠕇𡌶𣴓𤆵𤞤𤭢𧊒𧒽𨑨𪠽𪨊𫊻𫖃𫛶𫟷𫰡𫲨𬎆𬸅𭎂𮉫𮔅𮣲𮧵𰌂𰯼裋禥嫮𬂁

更改映射：

- [x] ⼾⾭

1.010 版已发行，关闭。

**Comment by jqk4388** [comment]
缺字：誒說

**Comment by Buernia** [comment]
> 缺字：誒說

目前是先满足简体中文需求。但有在考虑补全繁体字，可能还要另做字形统一的繁体版本，不过那都是远期的计划了。不知道港台有没有人在做这个。

“說” 可以先用 “説” 代替。
